r"""Contrast rules that are checked in the stylesheet's own text.

WHY NOT IN THE BROWSER. There was a browser test for this. It scanned
`document.styleSheets` for a rule with `background: var(--accent)` and
`color: #fff`, and it passed from the day it was written -- because CSSOM
normalises `#fff` to `rgb(255, 255, 255)`, so the comparison could never
match anything. It even carried a guard against being vacuous (it asserted it
had SEEN at least eight accent fills, which it had) and was vacuous anyway:
the reading was real and the test was wrong.

A rule it should have caught shipped under it. `.clip-fx-aim.is-on` filled a
shape with the accent and wrote `#fff` on it, and was found by eye while
doing something else.

The stylesheet is generated by `css.py`, so its text is right here. Scanned as
text, `#fff` is `#fff` and nothing can normalise it out from under the test.

WHAT THE NUMBERS ARE. Measured, not chosen -- the worst case for text over a
video frame is a WHITE frame, where white text on a black scrim scores:

    .28 -> 1.98    .35 -> 2.43    .50 -> 3.95
    .55 -> 4.74    .62 -> 6.19    .70 -> 8.45

so .54 is the floor for normal text at AA and .42 for large.
"""
from __future__ import annotations

import re

import pytest

from autostream.ui import css as css_mod


WHITE = {"#fff", "#ffffff", "white", "rgb(255,255,255)", "rgb(255, 255, 255)"}


@pytest.fixture(scope="module")
def sheet() -> str:
    text = getattr(css_mod, "CSS", None)
    if not isinstance(text, str):
        # Whatever the module calls it, the biggest string in it is the sheet.
        text = max((v for v in vars(css_mod).values() if isinstance(v, str)),
                   key=len)
    assert "--accent" in text, "that is not the stylesheet"
    return text


def rules(sheet: str):
    """-> (selector, body) for every rule, including inside @media.

    Crude on purpose: a real parser would be a dependency, and the only thing
    needed here is the text between one `{` and its `}` for a selector that
    is not an at-rule.
    """
    for m in re.finditer(r"([^{}@/][^{}]*?)\{([^{}]*)\}", sheet):
        sel, body = m.group(1).strip(), m.group(2)
        if not sel or sel.startswith("@"):
            continue
        yield sel, body


def _declared(body: str, prop: str) -> str | None:
    m = re.search(rf"(?:^|;)\s*{re.escape(prop)}\s*:\s*([^;]+)", body)
    return m.group(1).strip().lower() if m else None


# --------------------------------------------- white on an accent fill

def test_no_accent_fill_is_painted_with_hard_white(sheet):
    """White is not a contrast guarantee. Measured across the five themes,
    white on `--accent` scores 2.72, 1.23, 2.34, 1.87 and 5.85 -- so it fails
    AA in four of them, and on `carbon` 1.23:1 is not so much a contrast
    ratio as the absence of one. `--text-on-accent` is the token that exists
    for this and gives 6.94 to 15.99."""
    bad = []
    seen = 0
    for sel, body in rules(sheet):
        bg = (_declared(body, "background") or "") + \
             (_declared(body, "background-color") or "")
        if "var(--accent)" not in bg:
            continue
        seen += 1
        if (_declared(body, "color") or "") in WHITE:
            bad.append(sel)
    assert seen >= 8, (
        f"only {seen} accent fills found -- this test is reading the wrong "
        f"string and is checking nothing")
    assert not bad, (
        "accent fills painted with hard white instead of "
        "var(--text-on-accent): " + ", ".join(bad))


def test_the_guard_would_actually_catch_one(sheet):
    """THE POINT OF THIS FILE. The browser version of this test could not
    have failed, so it never did. This proves the matcher works by giving it
    the thing it is supposed to find."""
    planted = sheet + "\n.deliberately-wrong{background:var(--accent);color:#fff}\n"
    bad = [sel for sel, body in rules(planted)
           if "var(--accent)" in ((_declared(body, "background") or "") +
                                  (_declared(body, "background-color") or ""))
           and (_declared(body, "color") or "") in WHITE]
    assert bad == [".deliberately-wrong"], bad


# ------------------------------------------------- text over a video frame

def test_the_on_media_tokens_exist(sheet):
    for token in ("--on-media:", "--on-media-scrim:", "--on-media-scrim-soft:"):
        assert token in sheet, token


@pytest.mark.parametrize("token,least", [("--on-media-scrim:", 0.54),
                                         ("--on-media-scrim-soft:", 0.42)])
def test_each_scrim_is_dark_enough_for_what_it_carries(sheet, token, least):
    """A scrim is the whole contrast mechanism for text over gameplay: the
    frame underneath can be any colour at all, so the worst case is a white
    one and the alpha is what has to hold."""
    m = re.search(re.escape(token) + r"\s*rgba\(0,\s*0,\s*0,\s*([.\d]+)\)",
                  sheet)
    assert m, f"{token} is not an rgba black scrim any more"
    alpha = float(m.group(1))
    assert alpha >= least, (
        f"{token} is {alpha}, under the {least} that white text needs over a "
        f"white video frame")


def test_text_over_media_uses_the_tokens_rather_than_its_own_number(sheet):
    """EIGHT DIFFERENT ALPHAS WERE IN USE for this one job, and the lightest
    was behind 13px white text on the editor's frame handle: 2.43:1, which is
    unreadable over anything bright and had simply never been measured."""
    loose, seen = [], 0
    for sel, body in rules(sheet):
        seen += 1
        if (_declared(body, "color") or "") not in WHITE:
            continue
        bg = (_declared(body, "background") or "") + \
             (_declared(body, "background-color") or "")
        m = re.search(r"rgba\(0,\s*0,\s*0,\s*([.\d]+)\)", bg)
        if m:
            loose.append(f"{sel} (alpha {m.group(1)})")
    # NOT VACUOUS. An empty answer from a parser that read nothing looks
    # exactly like an empty answer from a stylesheet with nothing wrong in
    # it, and that is precisely how the browser version of this test stayed
    # green for its whole life. Counting white rules would not do: they were
    # all replaced by the token, so nearly none are left -- what has to be
    # true is that the sheet was parsed at all.
    assert seen >= 200, (
        f"only {seen} rules parsed out of the stylesheet -- this test is "
        f"reading the wrong string and is checking nothing")
    assert not loose, (
        "white text on a hand-written black scrim; use var(--on-media) with "
        "var(--on-media-scrim): " + ", ".join(loose))
